// Generated by https://quicktype.io
export interface ResourceResponseSEED {
    totalRegistros: number;
    pagina:         number;
    tamanoPagina:   number;
    recursos:       Recurso[];
}

export interface Serie {
    titulo:      Titulo;
    imagenUrl:   Color;
    color:       Color;
    descripcion: Color;
    recursos:    Array<Recurso | null>;
    autores:     any[];
    id:          number;
}

export interface Recurso {
    titulo:         string;
    descripcion:    string;
    referencia:     string;
    transcripcion:  null | string;
    medioSpotify:   null | string;
    medioYoutube:   null | string;
    mp3Url:         null | string;
    imagenUrl:      string;
    pdfUrl:         null | string;
    fechaCompleta:  string;
    visible:        boolean;
    resumen:        string;
    visitas:        number;
    reproducciones: number;
    etiquetas:      any[];
    fechaEmisionId: number;
    eventoId:       number | null;
    serieId:        number | null;
    autorId:        number;
    libroId:        number | null;
    autor:          Autor;
    fechaEmision:   FechaEmision;
    evento:         Evento | null;
    serie:          Serie | null;
    libro:          Evento | null;
    id:             number;
}

export enum Color {
    String = "string",
}

export enum Titulo {
    SerieRegular = "Serie Regular",
}

export interface Autor {
    id:     number;
    nombre: string;
}

export interface Evento {
    titulo: string;
    id:     number;
}

export interface FechaEmision {
    id:           number;
    fechaEmision: string;
}
